export const CATEGORIES = [
  { id: 'all', nameAr: 'الكل', nameEn: 'All', icon: '🏪' },
  { id: 'restaurant', nameAr: 'مطاعم', nameEn: 'Restaurants', icon: '🍽️' },
  { id: 'grocery', nameAr: 'بقالة', nameEn: 'Grocery', icon: '🛒' },
  { id: 'pharmacy', nameAr: 'صيدلية', nameEn: 'Pharmacy', icon: '💊' },
  { id: 'coffee', nameAr: 'قهوة', nameEn: 'Coffee', icon: '☕' },
  { id: 'sweets', nameAr: 'حلويات', nameEn: 'Sweets', icon: '🍰' },
  { id: 'electronics', nameAr: 'إلكترونيات', nameEn: 'Electronics', icon: '📱' },
  { id: 'fashion', nameAr: 'أزياء', nameEn: 'Fashion', icon: '👗' },
];

export const STORES = [
  {
    id: 1,
    nameAr: 'بهارات المطبخ',
    nameEn: 'Baharat Kitchen',
    category: 'restaurant',
    rating: 4.8,
    reviewCount: 324,
    deliveryTime: '25-35',
    deliveryFee: 5,
    minOrder: 30,
    emoji: '🍛',
    descriptionAr: 'أشهى المأكولات الشرقية والهندية',
    descriptionEn: 'Best Eastern & Indian cuisine',
    isOpen: true,
    isFeatured: true,
    badge: 'الأكثر طلباً',
    badgeEn: 'Most Ordered',
  },
  {
    id: 2,
    nameAr: 'برجرتينو',
    nameEn: 'Burgetino',
    category: 'restaurant',
    rating: 4.6,
    reviewCount: 218,
    deliveryTime: '20-30',
    deliveryFee: 7,
    minOrder: 25,
    emoji: '🍔',
    descriptionAr: 'برغر مميز بمكونات طازجة',
    descriptionEn: 'Premium burgers with fresh ingredients',
    isOpen: true,
    isFeatured: true,
    badge: 'جديد',
    badgeEn: 'New',
  },
  {
    id: 3,
    nameAr: 'سوبر ماركت الخليج',
    nameEn: 'Gulf Supermarket',
    category: 'grocery',
    rating: 4.5,
    reviewCount: 156,
    deliveryTime: '30-45',
    deliveryFee: 0,
    minOrder: 50,
    emoji: '🛒',
    descriptionAr: 'كل احتياجاتك في مكان واحد',
    descriptionEn: 'All your needs in one place',
    isOpen: true,
    isFeatured: false,
    badge: 'توصيل مجاني',
    badgeEn: 'Free Delivery',
  },
  {
    id: 4,
    nameAr: 'صيدلية الشفاء',
    nameEn: 'Al Shifa Pharmacy',
    category: 'pharmacy',
    rating: 4.9,
    reviewCount: 89,
    deliveryTime: '15-25',
    deliveryFee: 5,
    minOrder: 20,
    emoji: '💊',
    descriptionAr: 'أدوية وصحة ومستلزمات طبية',
    descriptionEn: 'Medicine, health & medical supplies',
    isOpen: true,
    isFeatured: false,
    badge: null,
    badgeEn: null,
  },
  {
    id: 5,
    nameAr: 'كافيه النخيل',
    nameEn: 'Al Nakheel Cafe',
    category: 'coffee',
    rating: 4.7,
    reviewCount: 445,
    deliveryTime: '20-30',
    deliveryFee: 8,
    minOrder: 20,
    emoji: '☕',
    descriptionAr: 'قهوة مميزة ومشروبات باردة وساخنة',
    descriptionEn: 'Premium coffee & hot/cold beverages',
    isOpen: false,
    isFeatured: true,
    badge: null,
    badgeEn: null,
  },
  {
    id: 6,
    nameAr: 'حلويات الأمير',
    nameEn: 'Al Amir Sweets',
    category: 'sweets',
    rating: 4.8,
    reviewCount: 201,
    deliveryTime: '30-40',
    deliveryFee: 5,
    minOrder: 35,
    emoji: '🍰',
    descriptionAr: 'حلويات شرقية وغربية راقية',
    descriptionEn: 'Premium Eastern & Western sweets',
    isOpen: true,
    isFeatured: false,
    badge: null,
    badgeEn: null,
  },
];

export const PRODUCTS = {
  1: [
    { id: 101, nameAr: 'دجاج بالبهارات', nameEn: 'Spiced Chicken', price: 38, emoji: '🍗', descriptionAr: 'دجاج مشوي مع أرز بسمتي', descriptionEn: 'Grilled chicken with basmati rice', category: 'رئيسية' },
    { id: 102, nameAr: 'بيريياني لحم', nameEn: 'Mutton Biryani', price: 45, emoji: '🍛', descriptionAr: 'أرز بيريياني مع لحم الضأن', descriptionEn: 'Biryani rice with mutton', category: 'رئيسية' },
    { id: 103, nameAr: 'كباب مشكل', nameEn: 'Mixed Kebab', price: 52, emoji: '🥩', descriptionAr: 'تشكيلة من الكباب المشوي', descriptionEn: 'Assorted grilled kebabs', category: 'رئيسية' },
    { id: 104, nameAr: 'سمبوسة', nameEn: 'Samosa', price: 15, emoji: '🥟', descriptionAr: 'سمبوسة محشية بالخضار', descriptionEn: 'Vegetable stuffed samosa', category: 'مقبلات' },
    { id: 105, nameAr: 'شاي هندي', nameEn: 'Masala Tea', price: 10, emoji: '🍵', descriptionAr: 'شاي بالحليب والبهارات', descriptionEn: 'Milk tea with spices', category: 'مشروبات' },
    { id: 106, nameAr: 'لاسي مانجو', nameEn: 'Mango Lassi', price: 15, emoji: '🥭', descriptionAr: 'لبن مانجو منعش', descriptionEn: 'Refreshing mango yogurt', category: 'مشروبات' },
  ],
  2: [
    { id: 201, nameAr: 'برغر كلاسيك', nameEn: 'Classic Burger', price: 32, emoji: '🍔', descriptionAr: 'برغر لحم مع خس وطماطم', descriptionEn: 'Beef burger with lettuce & tomato', category: 'برغر' },
    { id: 202, nameAr: 'برغر دجاج حار', nameEn: 'Spicy Chicken Burger', price: 30, emoji: '🌶️', descriptionAr: 'برغر دجاج حار مقرمش', descriptionEn: 'Crispy spicy chicken burger', category: 'برغر' },
    { id: 203, nameAr: 'بطاطس مقلية', nameEn: 'French Fries', price: 15, emoji: '🍟', descriptionAr: 'بطاطس ذهبية مقرمشة', descriptionEn: 'Golden crispy fries', category: 'جانبية' },
    { id: 204, nameAr: 'شيكسباكر', nameEn: 'Shakeburger', price: 45, emoji: '🧆', descriptionAr: 'برغر مزدوج مع جبنة', descriptionEn: 'Double patty with cheese', category: 'برغر' },
    { id: 205, nameAr: 'مشروب غازي', nameEn: 'Soft Drink', price: 8, emoji: '🥤', descriptionAr: 'كوكاكولا أو بيبسي', descriptionEn: 'Coca-Cola or Pepsi', category: 'مشروبات' },
  ],
  3: [
    { id: 301, nameAr: 'أرز بسمتي', nameEn: 'Basmati Rice', price: 12, emoji: '🍚', descriptionAr: 'أرز بسمتي هندي', descriptionEn: 'Indian basmati rice 1kg', category: 'حبوب' },
    { id: 302, nameAr: 'عصير برتقال', nameEn: 'Orange Juice', price: 8, emoji: '🍊', descriptionAr: 'عصير برتقال طازج', descriptionEn: 'Fresh orange juice 1L', category: 'عصائر' },
    { id: 303, nameAr: 'خبز عربي', nameEn: 'Arabic Bread', price: 5, emoji: '🫓', descriptionAr: 'خبز عربي طازج', descriptionEn: 'Fresh Arabic bread pack', category: 'خبز' },
    { id: 304, nameAr: 'حليب طازج', nameEn: 'Fresh Milk', price: 10, emoji: '🥛', descriptionAr: 'حليب طازج 1 لتر', descriptionEn: 'Fresh milk 1L', category: 'ألبان' },
    { id: 305, nameAr: 'بيض', nameEn: 'Eggs', price: 18, emoji: '🥚', descriptionAr: 'بيض طازج 12 حبة', descriptionEn: '12 fresh eggs', category: 'ألبان' },
  ],
};

export const OFFERS = [
  {
    id: 1,
    titleAr: 'خصم 30% على أول طلب',
    titleEn: '30% off your first order',
    subtitleAr: 'استخدم كود: SUMU30',
    subtitleEn: 'Use code: SUMU30',
    color: '#0F2A47',
    emoji: '🎉',
  },
  {
    id: 2,
    titleAr: 'توصيل مجاني',
    titleEn: 'Free Delivery',
    subtitleAr: 'لطلبات فوق 50 درهم',
    subtitleEn: 'Orders above 50 AED',
    color: '#C8A951',
    emoji: '🚀',
  },
  {
    id: 3,
    titleAr: 'اطلب الآن وادفع لاحقاً',
    titleEn: 'Order Now, Pay Later',
    subtitleAr: 'بدون فوائد مع سومو',
    subtitleEn: 'Interest-free with Sumu',
    color: '#1A6B4A',
    emoji: '💳',
  },
];

export const TAXI_TYPES = [
  {
    id: 'economy',
    nameAr: 'اقتصادي',
    nameEn: 'Economy',
    emoji: '🚗',
    descriptionAr: 'سيارة مريحة وبأسعار منخفضة',
    descriptionEn: 'Comfortable ride at low prices',
    pricePerKm: 2.5,
    baseFare: 10,
    eta: 3,
    seats: 4,
  },
  {
    id: 'comfort',
    nameAr: 'كومفورت',
    nameEn: 'Comfort',
    emoji: '🚙',
    descriptionAr: 'سيارة فئة أعلى مع مزايا إضافية',
    descriptionEn: 'Premium class car with extra features',
    pricePerKm: 3.5,
    baseFare: 15,
    eta: 5,
    seats: 4,
  },
  {
    id: 'premium',
    nameAr: 'بريميوم',
    nameEn: 'Premium',
    emoji: '🏎️',
    descriptionAr: 'تجربة فاخرة مع سائق محترف',
    descriptionEn: 'Luxury experience with professional driver',
    pricePerKm: 5,
    baseFare: 25,
    eta: 7,
    seats: 4,
  },
  {
    id: 'xl',
    nameAr: 'XL',
    nameEn: 'XL',
    emoji: '🚐',
    descriptionAr: 'سيارة كبيرة للمجموعات',
    descriptionEn: 'Large vehicle for groups',
    pricePerKm: 4,
    baseFare: 20,
    eta: 6,
    seats: 7,
  },
];
